name: C Code Check

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show available compiler
        run: |
          echo "cc -> $(which cc)"
          cc --version || true

      - name: Compile & Run all .c under exercises/
        run: |
          # find every .c under exercises/, even in subdirectories
          find exercises -type f -name '*.c' | while IFS= read -r file; do
            echo "🛠  Building $file"
            # strip .c to get the exe path
            exe="${file%.c}"
            # compile (clang or fallback to cc)
            ${CC:-clang} "$file" -o "$exe" -Wall -Wextra -Werror
            echo "▶️  Running $exe"
            "$exe"
            # clean up
            rm "$exe"
          done
