name: C Code Check

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show available compilers
        run: |
          echo "cc:"
          cc --version || true
          echo "clang:"
          clang --version || true

      - name: Compile and Run C Files
        run: |
          for file in *.c; do
            exe="${file%.c}"
            # use clang (or fallback to cc)
            ${CC:-clang} "$file" -o "$exe" -Wall -Wextra -Werror
            if [ $? -eq 0 ]; then
              echo "Running $exe…"
              ./"$exe"
              rm "$exe"
            else
              echo "❌ Failed to compile $file"
              exit 1
            fi
          done
